{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Student:\n",
    "    def __init__(self, id, name, surname, email, department,registrations,poll_submissions):\n",
    "        self.__id = id\n",
    "        self.__name = name\n",
    "        self.__surname = surname\n",
    "        self.__email = email\n",
    "        self.__department = department\n",
    "        self.__registration= []\n",
    "        self.__poll_submissions = []\n",
    "\n",
    "    # id Year attribute\n",
    "    @property\n",
    "    def id(self):\n",
    "        return self.__id\n",
    "\n",
    "    @id.setter\n",
    "    def id(self, value):\n",
    "        self.__id = value\n",
    "\n",
    "    # name attribute\n",
    "    @property\n",
    "    def name(self):\n",
    "        return self.__name\n",
    "\n",
    "    @name.setter\n",
    "    def name(self, value):\n",
    "        self.__name = value\n",
    "\n",
    "    # surname attribute\n",
    "    @property\n",
    "    def surname(self):\n",
    "        return self.__surname\n",
    "\n",
    "    @surname.setter\n",
    "    def student(self, value):\n",
    "        self.__surname = value\n",
    "\n",
    "    # email attribute\n",
    "    @property\n",
    "    def email(self):\n",
    "        return self.__email\n",
    "\n",
    "    @email.setter\n",
    "    def email(self, value):\n",
    "        self.__email = value\n",
    "\n",
    "    # department attribute\n",
    "    @property\n",
    "    def department(self):\n",
    "        return self.__department\n",
    "\n",
    "    @department.setter\n",
    "    def department(self, value):\n",
    "        self.__department = value\n",
    "        \n",
    "    # registrations attribute\n",
    "    @property\n",
    "    def registrations(self):\n",
    "        return self.__registrations\n",
    "\n",
    "    # poll_submissions attribute\n",
    "    @property\n",
    "    def poll_submissions(self):\n",
    "        return self.__poll_submissions"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
